server:
  port: 8081
  error:
    include-message: always

spring:
  data:
    redis:
      host: localhost
      port: 6379
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/user_db
#    password : Mahakal
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true
